### NEW PATIENT
POST http://localhost:3000/api/patients
Content-Type: application/json

{
  "name": "Franco Birocco",
  "dateOfBirth": "1989-04-10",
  "ssn": "35024684",
  "gender": "male",
  "occupation": "Biotechnologist"
}

### NEW ENTRE FOR PATIENT
POST http://localhost:3000/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2015-01-02",
  "type": "Hospital",
  "specialist": "MD House",
  "diagnosisCodes": ["S62.5"],
  "description":
    "Healing time appr. 2 weeks. patient doesn't remember how he got the injury.",
  "discharge": {
    "date": "2015-01-16",
    "criteria": "Thumb has healed."
  }
}


# {
#   "date": "2025-09-10",
#   "specialist": "Carreras",
#   "type": "OccupationalHealthcare",
#   "employerName": "Poder Judicial",
#   "description": "No sick leave for now."
# }


# {
#   "date": "2025-03-01",
#   "specialist": "Dr Loyber",
#   "type": "HealthCheck",
#   "description": "Regular anual check.",
#   "healthCheckRating": 3
# }